# Generated by Django 4.2.6 on 2023-10-27 07:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_code', models.CharField(max_length=255)),
                ('faculty_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_number', models.BigIntegerField(unique=True)),
                ('lecturer_name', models.CharField(max_length=200)),
                ('lecturer_contact', models.BigIntegerField()),
                ('batch_id', models.ManyToManyField(to='myapp.batches')),
            ],
            options={
                'verbose_name_plural': 'Lecturers',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], max_length=20)),
                ('course_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.courses')),
            ],
            options={
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_code', models.CharField(editable=False, max_length=3, unique=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Year must be at least 1.'), django.core.validators.MaxValueValidator(6, message='Year must be at most 6.')])),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Semester must be at least 1.'), django.core.validators.MaxValueValidator(3, message='Semester must be at most 3.')])),
            ],
            options={
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=255, unique=True)),
                ('unit_name', models.CharField(max_length=200)),
                ('batch_id', models.ManyToManyField(default=None, to='myapp.batches')),
                ('lecturer_id', models.ManyToManyField(default=None, to='myapp.lecturers')),
                ('time_id', models.ManyToManyField(to='myapp.time')),
            ],
            options={
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=255, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('batch_id', models.ManyToManyField(to='myapp.batches')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_marks', models.DecimalField(decimal_places=1, max_digits=5)),
                ('classification', models.CharField(max_length=100)),
                ('batch_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.batches')),
                ('course_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.courses')),
                ('faculty_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.faculties')),
                ('program_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.programs')),
                ('student_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.students')),
            ],
            options={
                'verbose_name_plural': 'StudentClassifications',
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(blank=True)),
                ('grade', models.CharField(blank=True, choices=[('', None), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default=None, editable=False, max_length=4)),
                ('remarks', models.CharField(blank=True, editable=False, max_length=100)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.students')),
                ('unit_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.units')),
            ],
            options={
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='faculty_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.faculties'),
        ),
        migrations.AddField(
            model_name='batches',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.programs'),
        ),
        migrations.AddField(
            model_name='batches',
            name='time_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.time'),
        ),
    ]
