# Generated by Django 4.2.6 on 2023-10-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_exams_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassification',
            name='average_marks',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentclassification',
            name='classification',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
