# Generated by Django 4.2.6 on 2023-11-07 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_exams_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
