# Generated by Django 4.2.6 on 2023-11-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_programs_program_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentclassification',
            unique_together={('student_id', 'program_id')},
        ),
    ]
